---
- name: Install PostgreSQL on all nodes
  hosts: primary,sync_standby,async_standby
  become: yes
  vars_files:
    - vars.yml
  tags: install
  roles:
    - install

- name: Configure primary node
  hosts: primary
  become: yes
  vars_files:
    - vars.yml
  tags: primary
  roles:
    - primary

- name: Configure sync standby node
  hosts: sync_standby
  become: yes
  vars_files:
    - vars.yml
  tags: sync_standby
  roles:
    - sync_standby

- name: Configure async standby node
  hosts: async_standby
  become: yes
  vars_files:
    - vars.yml
  tags: async_standby
  roles:
    - async_standby

- name: Configure backup on primary
  hosts: primary
  become: yes
  vars_files:
    - vars.yml
  tags: backup
  roles:
    - backup
